[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
 
[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"

[[headers]]
  for = "/admin/decap-cms.js"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
