[build]
  publish = "."
  command = ""
 
[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
 
[[redirects]]
  from = "/oauth/*"
  to = "/.netlify/functions/oauth/:splat"
  status = 200
 
[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Content-Security-Policy = "default-src 'self' https: data: blob:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; connect-src 'self' https://api.github.com https://github.com https://*.github.com; frame-src 'self' https://github.com https://*.github.com; frame-ancestors 'self'; object-src 'none'"

[[headers]]
  for = "/admin/decap-cms.js"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Content-Security-Policy = "default-src 'self' https: data: blob:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; connect-src 'self' https://api.github.com https://github.com https://*.github.com; frame-src 'self' https://github.com https://*.github.com; frame-ancestors 'self'; object-src 'none'"
