[build]
  publish = "."
  command = ""
  functions = "netlify/functions"

# Handle SPA routing - redirect all 404s to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Admin panel
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# OAuth endpoints
[[redirects]]
  from = "/.netlify/functions/oauth/*"
  to = "/.netlify/functions/oauth/:splat"
  status = 200
  force = true

# For Decap CMS OAuth flow
[[redirects]]
  from = "/oauth/*"
  to = "/.netlify/functions/oauth/:splat"
  status = 200
  force = true

# For direct function access (development)
[[redirects]]
  from = "/api/oauth/*"
  to = "/.netlify/functions/oauth/:splat"
  status = 200
  force = true

# Handle OAuth callbacks
[[redirects]]
  from = "/callback"
  to = "/.netlify/functions/oauth/callback"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://identity.netlify.com https://unpkg.com; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data: https:;"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
# CORS headers for OAuth endpoints
[[headers]]
  for = "/.netlify/functions/oauth/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"
    
# CORS headers for admin
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://identity.netlify.com https://unpkg.com; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data: https:;"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; font-src 'self' https: data:; img-src 'self' https: data:;"
