backend:
  name: github
  repo: joru10/website_CMS
  branch: main
  base_url: /api/oauth
  auth_endpoint: auth
  token_endpoint: access_token
  auth_type: pkce
  app_id: 'Ov23lilcBd8JkV3HWZbE'  # GitHub OAuth App Client ID
  site_domain: https://comfy-panda-0d488a.netlify.app
  auth_scope: 'repo,user'  # Explicitly set required scopes
  use_graphql: true
  # Debug settings
  debug: true
  # Enable the CMS to use the proxy for GitHub API calls
  proxy_url: /api/oauth/proxy
  # Important: Ensure the CMS knows we're using a proxy
  api_root: /api/oauth

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: test
    label: Test
    folder: content/test
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
