backend:
  name: git-gateway

media_folder: "static/uploads" # Media files will be stored in the repo under static/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /uploads

collections:
  - name: 'services'
    label: 'Services'
    folder: 'content/services'
    nested: { depth: 1 }
    extension: 'md'
    path: '{{slug}}/index'
    create: true
    slug: '{{slug}}'
    i18n: true
    format: 'frontmatter'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Description', name: 'description', widget: 'markdown', i18n: true }
      - { label: 'Icon', name: 'icon', widget: 'string' }
      - { label: 'Order', name: 'order', widget: 'number', value_type: 'int' }
      - { label: 'Featured', name: 'featured', widget: 'boolean' }
      - { label: 'Feature 1', name: 'feature1', widget: 'string', i18n: true }
      - { label: 'Feature 2', name: 'feature2', widget: 'string', i18n: true }
      - { label: 'Feature 3', name: 'feature3', widget: 'string', i18n: true }
  - name: 'translations'
    label: 'Translations'
    label_singular: 'Translation file'
    delete: false
    files:
      - file: 'translations/en.json'
        name: 'en'
        label: 'English'
        format: 'json'
        fields:
          - label: 'Strings'
            name: 'strings'
            widget: 'list'
            summary: '{{fields.key}}'
            fields:
              - { label: 'Key', name: 'key', widget: 'string' }
              - { label: 'Value', name: 'value', widget: 'string' }
      - file: 'translations/es.json'
        name: 'es'
        label: 'Español (EU)'
        format: 'json'
        fields:
          - label: 'Strings'
            name: 'strings'
            widget: 'list'
            summary: '{{fields.key}}'
            fields:
              - { label: 'Key', name: 'key', widget: 'string' }
              - { label: 'Value', name: 'value', widget: 'string' }
      - file: 'translations/fr.json'
        name: 'fr'
        label: 'Français (EU)'
        format: 'json'
        fields:
          - label: 'Strings'
            name: 'strings'
            widget: 'list'
            summary: '{{fields.key}}'
            fields:
              - { label: 'Key', name: 'key', widget: 'string' }
              - { label: 'Value', name: 'value', widget: 'string' }
  - name: 'blog'
    label: 'Blog Posts'
    folder: 'blog'
    create: true
    slug: '{{slug}}'
    format: 'frontmatter'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Summary', name: 'summary', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'education'
    label: 'Education Articles'
    folder: 'education'
    create: true
    slug: '{{slug}}'
    format: 'frontmatter'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Summary', name: 'summary', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'news'
    label: 'News'
    folder: 'news'
    create: true
    slug: '{{slug}}'
    format: 'frontmatter'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Summary', name: 'summary', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'cases'
    label: 'Case Studies'
    folder: 'cases'
    create: true
    slug: '{{slug}}'
    format: 'json'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Industry', name: 'industry', widget: 'string' }
      - { label: 'Challenge', name: 'challenge', widget: 'markdown' }
      - { label: 'Solution', name: 'solution', widget: 'markdown' }
      - { label: 'Outcome', name: 'outcome', widget: 'markdown' }
  - name: 'content'
    label: 'Site Content (claims, stats)'
    delete: false
    files:
      - file: 'content.json'
        label: 'Claims & Stats'
        name: 'claims'
        format: 'json'
        fields:
          - label: 'Data'
            name: 'data'
            widget: 'list'
            summary: '{{fields.key}}: {{fields.value}}'
            fields:
              - { label: 'Key', name: 'key', widget: 'string' }
              - { label: 'Value', name: 'value', widget: 'string' }
